### PR TITLE
Add `--hidden` flag

### PR DESCRIPTION
**Pull request by MagerValp**

### CODE REVIEW

**Comment by gregneagle** [comment]
LGTM.

**Comment by jelockwood** [comment]
Could the equivalent of this new feature be also added to the GUI version i.e. https://github.com/gregneagle/CreateUserPkg logically the screen for defining the new user would then include a tick box to say hide or not hide.

**Comment by gregneagle** [comment]
Sure it could be done. I have no plans to spend any time on that, however.

**Comment by MagerValp** [comment]
Someone has stepped up and made a GUI successor to CreateUserPkg, but it isn't quite yet ready to be announced publicly. Stay tuned.

**Pull request merged**
