### PR TITLE
Add token identity per #50

### PR DESCRIPTION
**Pull request by GregoryEAllen**
Also adds error reporting on existing UID collision

### CODE REVIEW

**Comment by gregneagle** [comment]
I'm not understanding the claim of "SecureToken" support. SecureToken to most admins means the account feature that allows unlocking FileVault volumes and modifying Startup Security settings on T2 Macs.

The smart card stuff authentication bits are, to my knowledge, completely different/separate from Apple's SecureToken.

As for Apple's SecureToken, there is more to adding a SecureToken to a user account than simply adding that attribute to AuthenticationAuthority. When the account has a SecureToken, that attribute is added to AuthenticationAuthority, but that attribute is not itself the SecureToken.

I feel like I'm missing something important here.

**Comment by gregneagle** [comment]
"postinstall checks for uid/username collision": when your code echos the message to stderr, where in the context of a package install does that message actually end up?

**Comment by GregoryEAllen** [comment]
You're right, SecureToken is used for multiple things. This small change simply adds some lines to the users's AuthenticationAuthority in the local DirectoryServices. That lets the user authenticate with a token identity hash in addition to the password. That lets them login, unlock screen, or escalate to admin privileges.

This doesn't touch FileVault, so the created user would not be able to unlock the disk at boot time. I think that's true with or without this patch.

**Comment by GregoryEAllen** [comment]
The message goes to `/var/log/install.log`. A dialog box would have been better.

These should probably be separate PRs.

**Comment by gregneagle** [comment]
I don't think a dialog box is wanted -- at least not by me! The intent (and least from me) is that these packages are installed by management systems like Munki or Jamf, or as part of a setup workflow via MDM or Imagr or bootstrappr/installr, or Two Canoe's MacDeployStick.

In all of these cases the actual install is happening via `/usr/sbin/installer` and not interactively via the GUI.

**Pull request closed without merging**
